# Generated by Django 5.1.3 on 2024-11-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
